### PR TITLE
Update gerrit-visible-review-comments for Gerrit 3.1.0

### PR DESCRIPTION
**Pull request by narbsy**
- Migrate reviewdb.client.* to entities.*
- Migrate EventListener to server.events

### CODE REVIEW

**Comment by oliver124810** [comment]
Thanks for the change! I would like to try it out before I merge it, it might take some time.

**Comment by narbsy** [comment]
Hey, no problems! 

We're running a release of this against our 3.1.0 installation.

The only issue we ran into was getting the `gerrit.config` picked up, but we think that's because we didn't restart the server. To work around this, we made some additional changes to read from `visible-review-comments.config`. Let me know if you're interested in those!

**Comment by oliver124810** [comment]
Of course! It would be great if you could push them.

**Comment by oliver124810** [comment]
I created two commits for this, one for the changes related to Gerrit 3.0 and another one for 3.1, just in case some needs the plugin for 3.0. Thank you for your help!

**Pull request closed without merging**
